version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
  celery:
    image: celery
    command: sh -c "
       celery -A innotter worker -l info"
    depends_on:
      - web
      - rabbitmq
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"