version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - database_data:/var/lib/postgresql/data
volumes:
  project:
  database_data: