# Generated by Django 4.0.5 on 2022-07-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_s3_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
